# version: '3.8'
services:
  mongodb:
    container_name: 'mongodb'
    image: 'mongo'
    volumes:
      - mydb:/data/db
    env_file:
      - MovieService/env/mongo.env
  movie:
    container_name: 'movie'
    build:
      context: ./
      dockerfile: Dockerfile.Movie
    ports:
      - '8081:8080'
    depends_on:
      - mongodb
  simplerestapi:
    container_name: 'simplerestapi'
    build:
     context: ./
     dockerfile: Dockerfile.SimpleRestApi
    ports:
      - '80:80'

volumes:
  mydb: