FROM golang:alpine3.20

WORKDIR /app

COPY SimpleRestApi/go.sum .

COPY SimpleRestApi/go.mod .

RUN go mod download

COPY SimpleRestApi .

RUN CGO_ENABLE=0 GOOS=linux go build -o ./simplerestapi

EXPOSE 80

ENTRYPOINT [ "./simplerestapi" ]